#define TKN_PROGRAM                      1
#define TKN_SEMI_COLON                   2
#define TKN_MAIN                         3
#define TKN_ID                           4
#define TKN_END                          5
#define TKN_VAR                          6
#define TKN_COLON                        7
#define TKN_COMMA                        8
#define TKN_INT                          9
#define TKN_FLOAT                       10
#define TKN_VOID                        11
#define TKN_LPAREN                      12
#define TKN_RPAREN                      13
#define TKN_LBRACKET                    14
#define TKN_RBRACKET                    15
#define TKN_LBRACE                      16
#define TKN_RBRACE                      17
#define TKN_ASSIGN                      18
#define TKN_IF                          19
#define TKN_WHILE                       20
#define TKN_PRINT                       21
#define TKN_STRING_CONST                22
#define TKN_ELSE                        23
#define TKN_INT_CONST                   24
#define TKN_FLOAT_CONST                 25
#define TKN_MULT                        26
#define TKN_DIV                         27
#define TKN_PLUS                        28
#define TKN_MINUS                       29
#define TKN_LT                          30
#define TKN_GT                          31
#define TKN_NE                          32
#define TKN_DO                          33
